name: Deploy to Minikube using Github Actions

on: 
  push:        # triggers on any push
    branches:
      - main   # replace 'main' with your branch name if different

jobs:
  job1:
    runs-on: ubuntu-latest
    name: deploy node.js app to minikube
    steps:
    - uses: actions/checkout@v2

    # Log in to Docker Hub using secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Start Minikube
    - name: Start minikube
      uses: medyagh/setup-minikube@master

    # Check cluster
    - name: Try the cluster
      run: kubectl get pods -A

    # Deploy your app
    - name: Deploy to minikube
      run: |
        kubectl apply -f k8-node-app.yaml

    # Wait until pod is ready
    - name: Wait for Pod to be ready
      run: |
        kubectl wait --for=condition=ready pod -l app=nodejs-app --timeout=180s

    # Check pod status
    - name: Check pod status
      run: |
        kubectl get pods -A
        kubectl describe pods -l app=nodejs-app

    # Check pod logs
    - name: Check pod logs
      run: |
        kubectl logs -l app=nodejs-app

    # Test service URLs
    - name: Test service URLs
      run: |
        minikube service list
        minikube service nodejs-app --url
