name: Deploy to Minikube using Github Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: deploy node.js app to minikube
    steps:
    - uses: actions/checkout@v2

    # Start Minikube
    - name: Start minikube
      uses: medyagh/setup-minikube@master

    # Check cluster
    - name: Try the cluster
      run: kubectl get pods -A

    # Load Docker image into Minikube
    - name: Load Docker image into Minikube
      run: |
        eval $(minikube -p minikube docker-env)
        docker pull vtejaswinig/nodejs-app:latest
        minikube image load vtejaswinig/nodejs-app:latest

    # Deploy your app
    - name: Deploy to minikube
      run: |
        kubectl apply -f k8-node-app.yaml

    # Debug pod creation (important for errors)
    - name: Debug pod creation
      run: |
        kubectl get pods -A
        kubectl describe pod -l app=nodejs-app
        kubectl get events --sort-by='.lastTimestamp'

    # Wait until pod is ready
    - name: Wait for Pod to be ready
      run: |
        kubectl wait --for=condition=ready pod -l app=nodejs-app --timeout=300s || \
        (echo "Pods did not become ready. Showing logs:" && \
         kubectl logs -l app=nodejs-app --all-containers && exit 1)

    # Check pod logs
    - name: Check pod logs
      run: |
        kubectl logs -l app=nodejs-app --all-containers

    # Test service URLs
    - name: Test service URLs
      run: |
        minikube service list
        minikube service nodejs-app --url

