name: Deploy Node.js App to Minikube

on:
  push:
    branches:
      - main  # or the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build, Push, and Deploy Node.js App
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Start Minikube
      - name: Start Minikube
        uses: medyagh/setup-minikube@master

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t vtejaswinig/nodejs-app:latest .
          docker push vtejaswinig/nodejs-app:latest

      # Deploy to Minikube
      - name: Deploy Node.js app
        run: kubectl apply -f k8-node-app.yaml

      # Wait until pod is ready
      - name: Wait for pod to be ready
        run: kubectl wait --for=condition=ready pod -l app=nodejs-app --timeout=180s

      # Check pod status
      - name: Check pod status
        run: |
          kubectl get pods -A
          kubectl describe pods -l app=nodejs-app

      # Check pod logs
      - name: Check pod logs
        run: kubectl logs -l app=nodejs-app

      # Test service URLs
      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
